source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "9.0"
use_frameworks!

target 'WeatherApp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks

  # Pods for WeatherApp
    pod 'ChameleonFramework/Swift'
    pod 'SwiftyJSON'
    pod 'ARSLineProgress', '~> 1.0'
    pod 'SkyFloatingLabelTextField', '~> 1.0'
    pod 'MGSwipeTableCell'
    pod 'Eureka', '~> 1.7'
    pod 'IQKeyboardManagerSwift'
    pod 'Alamofire', '~> 3.4'
    pod 'SimpleKeychain'
    pod "AsyncSwift"
end
